import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.example.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Finance</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-8">hello</main>
      {data && JSON.stringify(data)}
    </>
  );
};

export default Home;
